[package]
name = "nixme"
version = "0.1.0"
authors = ["Mateusz Czapli≈Ñski <czapkofan@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
mock-io = { git = "https://github.com/akavel/mock-io" }

